apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: at2d6mwvt-java-springboot
  janus-idp.io/tekton: at2d6mwvt-java-springboot
  backstage.io/kubernetes-id: at2d6mwvt-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: at2d6mwvt-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
